/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewPostRouteImport } from './routes/new-post'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as EditIdRouteImport } from './routes/edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPostRoute = NewPostRouteImport.update({
  id: '/new-post',
  path: '/new-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-post': typeof NewPostRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/edit/$id': typeof EditIdRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-post': typeof NewPostRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/edit/$id': typeof EditIdRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-post': typeof NewPostRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/edit/$id': typeof EditIdRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-post'
    | '/profile'
    | '/register'
    | '/blogs/$slug'
    | '/edit/$id'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-post'
    | '/profile'
    | '/register'
    | '/blogs/$slug'
    | '/edit/$id'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-post'
    | '/profile'
    | '/register'
    | '/blogs/$slug'
    | '/edit/$id'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NewPostRoute: typeof NewPostRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  EditIdRoute: typeof EditIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-post': {
      id: '/new-post'
      path: '/new-post'
      fullPath: '/new-post'
      preLoaderRoute: typeof NewPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NewPostRoute: NewPostRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  EditIdRoute: EditIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
